import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      ink: 'var(--ink)',
      cream: 'var(--cream)',
      rink: 'var(--rink)',
      puck: 'var(--puck)',
      blood: 'var(--blood)',
      'ink-muted': 'var(--ink-muted)',
      'ink-quiet': 'var(--ink-quiet)',
      'ink-hint': 'var(--ink-hint)',
      'ink-rule': 'var(--ink-rule)',
      'ink-hair': 'var(--ink-hair)',
      'cream-muted': 'var(--cream-muted)',
      'cream-quiet': 'var(--cream-quiet)',
      'cream-rule': 'var(--cream-rule)',
      white: '#FFFFFF',
      transparent: 'transparent',
      current: 'currentColor',
    },
    spacing: {
      '0': '0px',
      '0.5': '4px',
      '1': '8px',
      '1.5': '12px',
      '2': '16px',
      '3': '24px',
      '4': '32px',
      '6': '48px',
      '8': '64px',
      '10': '80px',
      '15': '120px',
      '20': '160px',
    },
    screens: {
      sm: '640px',
      md: '1024px',
      lg: '1440px',
    },
    fontFamily: {
      display: ['Oswald', 'sans-serif'],
      body: ['Inter Tight', 'sans-serif'],
    },
    fontSize: {
      'xs': ['11px', { lineHeight: '1.4', letterSpacing: '0.12em' }],
      'sm': ['13px', { lineHeight: '1.5', letterSpacing: '0.02em' }],
      'base': ['16px', { lineHeight: '1.55' }],
      'lg': ['20px', { lineHeight: '1.2' }],
      'xl': ['26px', { lineHeight: '1.2', letterSpacing: '0.005em' }],
      '2xl': ['32px', { lineHeight: '1.1', letterSpacing: '-0.005em' }],
      '3xl': ['40px', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
      '4xl': ['56px', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
      '5xl': ['88px', { lineHeight: '0.95', letterSpacing: '-0.015em' }],
    },
    extend: {},
  },
  plugins: [],
} satisfies Config
